import {MigrationInterface, QueryRunner} from "typeorm";

export class game1596108130561 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(1, 'Doubutsu Shogi', 'doubutsu-shogi', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(3, 'Filler', 'filler', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(4, 'Bagh Chal', 'bagh-chal', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(5, 'Italian Damone', 'damone', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(6, 'Fox and Geese', 'foxnguse', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(7, 'French Military Game', 'french-military', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(8, 'Horn Chess', 'horn-chess', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(9, 'Kharbaga', 'kharbaga', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(10, 'Light Off', 'light-off', 1, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(11, 'Magyar Dama', 'magyar-dama', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(12, 'Maharadja', 'maharadja', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(13, 'NetWalk', 'netwalk', 1, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(14, 'Shisima', 'shisima', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(15, 'Tactical tic-tac-toe', 'uxo', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(16, 'Chess Go', 'chess-go', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(17, 'Go', 'go-19x19', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(21, 'Dual Go', 'dual-go', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(22, 'Checkers', 'russian-checkers', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(23, 'XiangQi', 'xiangqi', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(24, 'Column Checkers', 'column-checkers', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(25, 'Shogi', 'shogi', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time, max_selector) values(26, 'Reversi', 'reversi', 2, 0, 1000, 10)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(27, 'Stratego', 'stratego', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(28, 'Spock', 'spock', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(29, 'Hex', 'hex', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(30, 'Chess', 'chess', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(31, 'Mancala', 'oware', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(32, 'Alquerque', 'alquerque', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time, is_hidden) values(33, 'Banqi', 'banqi-chinese', 2, 0, 1000, 1)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(34, 'Passive Chess', 'passive-chess', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(35, 'Morris', 'morris-9', 2, 0, 1000)`);
        await queryRunner.query(`insert into games(id, name, filename, players_total, main_time, additional_time) values(36, 'Cheskers', 'cheskers-8x8', 2, 0, 1000)`);

        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(1, 17, 'Go (9x9)', 'go-9x9', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(2, 17, 'Go (19x19)', 'go-19x19', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, max_selector) values(3, 22, 'Russian Checkers', 'russian-checkers', 2, 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(4, 22, 'International Checkers', 'international-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(5, 22, 'Frisian Checkers', 'frisian-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(6, 22, '80 Cells Checkers', '80-cells-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(7, 23, 'XiangQi', 'xiangqi', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(8, 23, 'YitongQi', 'yitongqi', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(9, 23, 'Five Tigers', 'tigers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(10, 25, 'Shogi', 'shogi', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(11, 25, 'Mini Shogi', 'mini-shogi', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(12, 23, 'Dark XiangQi', 'dark-chinese-chess', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(13, 17, 'Paper Go', 'paper-go', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(14, 17, 'Atari Go', 'atari-go', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(15, 17, 'MarGo', 'margo', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(16, 27, 'Stratego', 'stratego', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(17, 27, 'Jungle', 'jungle', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(18, 31, 'Oware', 'oware', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(19, 31, 'Cross Wari', 'cross-wari', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(20, 31, 'Toguz Kumalak', 'toguz-kumalak', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(21, 27, 'Luzhanqi', 'luzhanqi', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(22, 27, 'Game of Generals', 'gog', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(23, 32, 'Alquerque', 'alquerque', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(24, 32, 'Fanorona', 'fanorona', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(25, 32, 'Zamma', 'zamma', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(26, 32, 'Dablot Asele', 'dablot-asele', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(27, 32, 'Dablot Frostviken (Child)', 'dablot-child', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(28, 32, 'Dablot Dares', 'dablot-dares', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(29, 32, 'Dablot Frostviken', 'dablot-frostviken', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(30, 32, 'Dablot Prejjesne', 'dablot-prejjesne', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, max_selector) values(31, 30, 'Chess', 'chess', 2, 8)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, max_selector) values(32, 30, 'Courier Chess', 'courier-chess', 2, 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(33, 30, 'Fighting Chess', 'fighting-chess', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(34, 30, 'Makruk', 'makruk', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(35, 24, 'Column Checkers', 'column-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(36, 24, 'Lasca', 'laska', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(37, 24, 'Stapeldammen', 'stapeldammen', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, max_selector) values(38, 30, 'Shatranj', 'shatranj', 2, 93)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(39, 33, 'Banqi (Chinese)', 'banqi-chinese', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(40, 33, 'Banqi (Taiwanese)', 'banqi-taiwanese', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(41, 33, 'Banqi (10x9)', 'banqi-large', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(42, 32, 'Kolowisi Awithlaknannai', 'serpents', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(43, 34, 'Passive Chess', 'passive-chess', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(44, 34, 'Littera Chinese Chess', 'litter-chess', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(45, 22, 'English Checkers', 'english-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(46, 22, 'Turkish Dama', 'turkish-dama', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(47, 22, 'Constitutional Checkers', 'constitutional-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(48, 22, 'Stavropol Checkers', 'stavropol-checkers', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(49, 35, 'Nine Men's Morris', 'morris-9', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(50, 35, 'Three Men's Morris', 'triangle', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(51, 35, 'Windmill', 'windmill', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(52, 35, 'Eight Men's Morris', 'morris-8', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(53, 35, 'Seven Men's Morris', 'morris-7', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(54, 35, 'Twelve Men's Morris', 'morris-12', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(55, 35, 'Morabaraba', 'morabaraba', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(56, 30, 'Turnover', 'turnover', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(57, 23, 'Janggi', 'janggi', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(58, 30, 'Sittuyin', 'sittuyin', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(59, 30, 'Short Assize', 'short-assize', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(60, 36, 'Cheskers (8x8)', 'cheskers-8x8', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(61, 36, 'Cheskers (9x9)', 'cheskers-9x9', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, max_selector) values(62, 36, 'Cheskers (10x10)', 'cheskers-10x10', 2, 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, max_selector) values(63, 36, 'Belarusian Chess', 'belarusian-chess', 2, 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total, is_hidden) values(64, 30, 'Dark Chess', 'dark-chess', 2, 1)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(65, 30, 'Progressive Chess', 'progressive-chess', 2)`);
        await queryRunner.query(`insert into game_variants(id, game_id, name, filename, players_total) values(66, 30, 'Hiashatar', 'hiashatar', 2)`);

        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(1, 23, 'European', '', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(2, 23, 'Chinese', '-kanji', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(3, 23, 'Opposite', '-black', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(4, 16, 'European', '', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(5, 16, 'Chinese', '-kanji', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(6, 25, 'European', '', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(7, 25, 'Japanese', '-kanji', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(8, 25, 'Opposite', '-north', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(9, 27, 'Opposite', '-blue', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(10, 22, 'Opposite', '-black', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(11, 24, 'Opposite', '-black', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(12, 28, 'Opposite', '-red', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(13, 30, 'Opposite', '-black', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(14, 31, 'Opposite', '-north', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(15, 23, 'Seeds', '', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(16, 23, 'Digits', '-alt', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(17, 32, 'Opposite', '-north', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(18, 33, 'European', '', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(19, 33, 'Chinese', '-kanji', null)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(20, 34, 'Opposite', '-black', 2)`);
        await queryRunner.query(`insert into game_styles(id, game_id, name, suffix, player_num) values(21, 36, 'Opposite', '-black', 2)`);

        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(1, 'doubutsu-shogi', null, 'doubutsu-shogi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(2, 'atari-go', null, 'atari-go')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(3, 'chess-go', null, 'chess-go')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(4, 'go-9x9', null, 'go-9x9')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(5, 'go-19x19', null, 'go-19x19')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(6, 'jungle', null, 'jungle')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(7, 'margo', null, 'margo')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(8, 'paper-go', null, 'paper-go')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(9, 'dual-go', null, 'dual-go')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(10, 'russian-checkers', 1, 'russian-checkers-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(11, 'international-checkers', null, 'international-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(12, 'frisian-checkers', null, 'frisian-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(13, '80-cells-checkers', null, '80-cells-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(14, 'xiangqi', null, 'xiangqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(15, 'column-checkers', null, 'column-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(16, 'shogi', null, 'shogi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(17, 'reversi', 1, 'reversi-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(18, 'reversi', 2, 'reversi-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(19, 'reversi', 3, 'reversi-3')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(20, 'reversi', 4, 'reversi-4')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(21, 'reversi', 5, 'reversi-5')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(22, 'reversi', 6, 'reversi-6')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(23, 'reversi', 7, 'reversi-7')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(24, 'reversi', 8, 'reversi-8')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(25, 'reversi', 9, 'reversi-9')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(26, 'reversi', 10, 'reversi-10')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(27, 'xiangqi-kanji', null, 'xiangqi-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(28, 'chess-go-kanji', null, 'chess-go-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(29, 'yitongqi', null, 'yitongqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(30, 'yitongqi-kanji', null, 'yitongqi-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(31, 'tigers', null, 'tigers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(32, 'tigers-kanji', null, 'tigers-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(33, 'shogi-kanji', null, 'shogi-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(34, 'mini-shogi', null, 'mini-shogi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(35, 'mini-shogi-kanji', null, 'mini-shogi-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(36, 'dark-chinese-chess', null, 'dark-chinese-chess')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(37, 'dark-chinese-chess-kanji', null, 'dark-chinese-chess-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(38, 'stratego', null, 'stratego')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(39, 'spock', null, 'spock')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(40, 'hex', null, 'hex')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(41, 'chess', 1, 'chess-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(42, 'oware', null, 'oware')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(43, 'oware-alt', null, 'oware-alt')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(44, 'cross-wari', null, 'oware')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(45, 'cross-wari-alt', null, 'oware-alt')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(46, 'toguz-kumalak', null, 'toguz-kumalak')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(47, 'toguz-kumalak-alt', null, 'toguz-kumalak-alt')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(48, 'luzhanqi', null, 'luzhanqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(49, 'gog', null, 'gog')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(50, 'alquerque', null, 'alquerque')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(51, 'fanorona', null, 'fanorona')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(52, 'zamma', null, 'zamma')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(53, 'dablot-asele', null, 'dablot-asele')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(54, 'dablot-child', null, 'dablot-child')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(55, 'dablot-dares', null, 'dablot-dares')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(56, 'dablot-frostviken', null, 'dablot-frostviken')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(57, 'dablot-prejjesne', null, 'dablot-prejjesne')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(58, 'courier-chess', 1, 'courier-chess-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(59, 'courier-chess', 2, 'courier-chess-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(60, 'fighting-chess', null, 'chess')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(61, 'makruk', null, 'makruk')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(62, 'laska', null, 'laska')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(63, 'stapeldammen', null, 'stapeldammen')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(64, 'shatranj', 1, 'shatranj-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(65, 'shatranj', 2, 'shatranj-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(66, 'shatranj', 3, 'shatranj-3')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(67, 'shatranj', 4, 'shatranj-4')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(68, 'shatranj', 5, 'shatranj-5')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(69, 'shatranj', 6, 'shatranj-6')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(70, 'shatranj', 7, 'shatranj-7')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(71, 'shatranj', 8, 'shatranj-8')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(72, 'shatranj', 9, 'shatranj-9')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(73, 'shatranj', 10, 'shatranj-10')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(74, 'shatranj', 11, 'shatranj-11')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(75, 'shatranj', 12, 'shatranj-12')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(76, 'shatranj', 13, 'shatranj-13')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(77, 'shatranj', 14, 'shatranj-14')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(78, 'shatranj', 15, 'shatranj-15')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(79, 'shatranj', 16, 'shatranj-16')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(80, 'shatranj', 17, 'shatranj-17')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(81, 'shatranj', 18, 'shatranj-18')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(82, 'shatranj', 19, 'shatranj-19')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(83, 'shatranj', 20, 'shatranj-20')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(84, 'shatranj', 21, 'shatranj-21')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(85, 'shatranj', 22, 'shatranj-22')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(86, 'shatranj', 23, 'shatranj-23')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(87, 'shatranj', 24, 'shatranj-24')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(88, 'shatranj', 25, 'shatranj-25')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(89, 'shatranj', 26, 'shatranj-26')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(90, 'shatranj', 27, 'shatranj-27')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(91, 'shatranj', 28, 'shatranj-28')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(92, 'shatranj', 29, 'shatranj-29')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(93, 'shatranj', 30, 'shatranj-30')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(94, 'shatranj', 31, 'shatranj-31')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(95, 'shatranj', 32, 'shatranj-32')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(96, 'shatranj', 33, 'shatranj-33')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(97, 'shatranj', 34, 'shatranj-34')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(98, 'shatranj', 35, 'shatranj-35')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(99, 'shatranj', 36, 'shatranj-36')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(100, 'shatranj', 37, 'shatranj-37')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(101, 'shatranj', 38, 'shatranj-38')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(102, 'shatranj', 39, 'shatranj-39')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(103, 'shatranj', 40, 'shatranj-40')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(104, 'shatranj', 41, 'shatranj-41')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(105, 'shatranj', 42, 'shatranj-42')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(106, 'shatranj', 43, 'shatranj-43')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(107, 'shatranj', 44, 'shatranj-44')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(108, 'shatranj', 45, 'shatranj-45')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(109, 'shatranj', 46, 'shatranj-46')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(110, 'shatranj', 47, 'shatranj-47')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(111, 'shatranj', 48, 'shatranj-48')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(112, 'shatranj', 49, 'shatranj-49')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(113, 'shatranj', 50, 'shatranj-50')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(114, 'shatranj', 51, 'shatranj-51')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(115, 'shatranj', 52, 'shatranj-52')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(116, 'shatranj', 53, 'shatranj-53')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(117, 'shatranj', 54, 'shatranj-54')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(118, 'shatranj', 55, 'shatranj-55')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(119, 'shatranj', 56, 'shatranj-56')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(120, 'shatranj', 57, 'shatranj-57')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(121, 'shatranj', 58, 'shatranj-58')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(122, 'shatranj', 59, 'shatranj-59')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(123, 'shatranj', 60, 'shatranj-60')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(124, 'shatranj', 61, 'shatranj-61')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(125, 'shatranj', 62, 'shatranj-62')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(126, 'shatranj', 63, 'shatranj-63')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(127, 'shatranj', 64, 'shatranj-64')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(128, 'shatranj', 65, 'shatranj-65')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(129, 'shatranj', 66, 'shatranj-66')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(130, 'shatranj', 67, 'shatranj-67')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(131, 'shatranj', 68, 'shatranj-68')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(132, 'shatranj', 69, 'shatranj-69')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(133, 'shatranj', 70, 'shatranj-70')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(134, 'shatranj', 71, 'shatranj-71')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(135, 'shatranj', 72, 'shatranj-72')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(136, 'shatranj', 73, 'shatranj-73')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(137, 'shatranj', 74, 'shatranj-74')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(138, 'shatranj', 75, 'shatranj-75')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(139, 'shatranj', 76, 'shatranj-76')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(140, 'shatranj', 77, 'shatranj-77')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(141, 'shatranj', 78, 'shatranj-78')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(142, 'shatranj', 79, 'shatranj-79')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(143, 'shatranj', 80, 'shatranj-80')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(144, 'shatranj', 81, 'shatranj-81')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(145, 'shatranj', 82, 'shatranj-82')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(146, 'shatranj', 83, 'shatranj-83')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(147, 'shatranj', 84, 'shatranj-84')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(148, 'shatranj', 85, 'shatranj-85')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(149, 'shatranj', 86, 'shatranj-86')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(150, 'shatranj', 87, 'shatranj-87')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(151, 'shatranj', 88, 'shatranj-88')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(152, 'shatranj', 89, 'shatranj-89')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(153, 'shatranj', 90, 'shatranj-90')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(154, 'shatranj', 91, 'shatranj-91')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(155, 'shatranj', 92, 'shatranj-92')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(156, 'shatranj', 93, 'shatranj-93')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(157, 'banqi-chinese', null, 'banqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(158, 'banqi-chinese-kanji', null, 'banqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(159, 'banqi-taiwanese', null, 'banqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(160, 'banqi-taiwanese-kanji', null, 'banqi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(161, 'banqi-large', null, 'banqi-large')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(162, 'banqi-large-kanji', null, 'banqi-large')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(163, 'serpents', null, 'serpents')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(164, 'litter-chess', null, 'litter')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(165, 'passive-chess', null, 'passive')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(166, 'morris-9', null, '9-men')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(167, 'triangle', null, '3-men')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(168, 'english-checkers', null, 'english-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(169, 'turkish-dama', null, 'turkish-dama')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(170, 'constitutional-checkers', null, 'international-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(171, 'stavropol-checkers', null, 'russian-checkers')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(172, 'windmill', null, 'windmill')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(173, 'morris-8', null, '8-men')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(174, 'morris-7', null, '7-men')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(175, 'morris-12', null, '12-men')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(176, 'morabaraba', null, 'morabaraba')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(177, 'turnover', null, 'turnover')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(178, 'janggi', null, 'janggi')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(179, 'janggi-kanji', null, 'janggi-kanji')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(180, 'sittuyin', null, 'sittuyin')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(181, 'short-assize', null, 'short-assize')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(182, 'cheskers-8x8', null, 'cheskers-8x8')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(183, 'cheskers-9x9', null, 'cheskers-9x9')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(184, 'cheskers-10x10', 1, 'cheskers-10x10-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(185, 'cheskers-10x10', 2, 'cheskers-10x10-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(186, 'belarusian-chess', 1, 'belarusian-chess-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(187, 'belarusian-chess', 2, 'belarusian-chess-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(188, 'dark-chess', null, 'dark-chess')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(189, 'chess', 2, 'chess-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(190, 'chess', 3, 'chess-3')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(191, 'chess', 4, 'chess-4')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(192, 'chess', 5, 'chess-5')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(193, 'chess', 6, 'chess-6')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(194, 'chess', 7, 'chess-7')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(195, 'chess', 8, 'chess-8')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(196, 'russian-checkers', 2, 'russian-checkers-2')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(197, 'progressive-chess', null, 'chess-1')`);
        await queryRunner.query(`insert into game_previews(id, filename, selector_value, preview) values(198, 'hiashatar', null, 'hiashatar')`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`delete from game_previews`);
        await queryRunner.query(`delete from game_styles`);
        await queryRunner.query(`delete from game_variants`);
        await queryRunner.query(`delete from games`);
    }
}
